[2025-04-23T06:13:36.750+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: user_etl_dag.extract_users scheduled__2025-04-22T05:22:05.986111+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-04-23T06:13:37.717+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
