[2025-04-23T00:00:13.112+0000] {processor.py:157} INFO - Started process (PID=2875) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:00:14.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:00:18.255+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:00:16.781+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:01:22.570+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:02:07.888+0000] {processor.py:157} INFO - Started process (PID=2876) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:02:07.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:02:08.056+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:02:08.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:02:12.832+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:05:14.354+0000] {processor.py:157} INFO - Started process (PID=2877) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:05:14.430+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:05:14.518+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:05:14.473+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:05:44.712+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:07:14.147+0000] {processor.py:157} INFO - Started process (PID=2878) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:07:16.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:07:16.751+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:07:16.656+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:09:46.975+0000] {processor.py:157} INFO - Started process (PID=2879) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:09:47.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:09:48.790+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:09:48.448+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:11:36.347+0000] {processor.py:157} INFO - Started process (PID=2880) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:11:36.369+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:11:36.546+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:11:36.408+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:11:43.030+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:13:16.644+0000] {processor.py:157} INFO - Started process (PID=2881) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:13:16.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:13:16.935+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:13:16.910+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:13:28.020+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:16:39.839+0000] {processor.py:157} INFO - Started process (PID=2882) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:16:41.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:16:42.323+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:16:41.912+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:18:18.086+0000] {processor.py:157} INFO - Started process (PID=2883) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:18:20.212+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:18:22.012+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:18:21.721+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:20:56.713+0000] {processor.py:157} INFO - Started process (PID=2892) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:20:56.963+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:20:57.322+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:20:57.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:23:23.901+0000] {processor.py:157} INFO - Started process (PID=2893) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:23:24.834+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:23:25.211+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:23:25.055+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:24:31.554+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:25:09.676+0000] {processor.py:157} INFO - Started process (PID=2894) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:25:09.783+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:25:09.799+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:25:09.796+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:27:45.022+0000] {processor.py:157} INFO - Started process (PID=2895) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:27:46.113+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:27:49.570+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:27:49.232+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:29:01.617+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:29:41.109+0000] {processor.py:157} INFO - Started process (PID=2896) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:29:41.680+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:29:42.099+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:29:41.836+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:32:03.463+0000] {processor.py:157} INFO - Started process (PID=2897) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:32:03.913+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:32:06.310+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:32:05.183+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:32:28.242+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:33:41.438+0000] {processor.py:157} INFO - Started process (PID=2898) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:33:41.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:33:41.675+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:33:41.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:33:49.235+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:36:24.503+0000] {processor.py:157} INFO - Started process (PID=2899) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:36:26.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:36:26.898+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:36:26.776+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:40:35.517+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:42:13.088+0000] {processor.py:157} INFO - Started process (PID=2900) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:42:13.294+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:43:39.492+0000] {processor.py:157} INFO - Started process (PID=2901) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:43:39.618+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:43:39.844+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:43:39.659+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:43:52.901+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:46:21.413+0000] {processor.py:157} INFO - Started process (PID=2902) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:46:22.891+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:46:24.294+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:46:24.220+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:47:56.040+0000] {processor.py:157} INFO - Started process (PID=2903) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:47:56.236+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:47:56.527+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:47:56.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:48:06.415+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:49:56.221+0000] {processor.py:157} INFO - Started process (PID=2904) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:49:56.314+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:49:56.540+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:49:56.369+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:51:13.782+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:52:47.605+0000] {processor.py:157} INFO - Started process (PID=2905) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:52:47.903+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:52:48.394+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:52:48.075+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:52:54.914+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:55:38.416+0000] {processor.py:157} INFO - Started process (PID=2906) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:55:38.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:55:39.360+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:55:39.060+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:58:57.512+0000] {processor.py:157} INFO - Started process (PID=2907) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:58:58.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T00:58:59.020+0000] {logging_mixin.py:151} INFO - [2025-04-23T00:58:58.900+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T00:59:09.591+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:06:58.783+0000] {processor.py:157} INFO - Started process (PID=2908) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:06:59.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T02:06:59.741+0000] {logging_mixin.py:151} INFO - [2025-04-23T02:06:59.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:09:27.288+0000] {processor.py:157} INFO - Started process (PID=2909) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:09:28.073+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T02:09:28.337+0000] {logging_mixin.py:151} INFO - [2025-04-23T02:09:28.189+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:09:38.574+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:12:14.558+0000] {processor.py:157} INFO - Started process (PID=2910) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:12:14.662+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T02:12:14.746+0000] {logging_mixin.py:151} INFO - [2025-04-23T02:12:14.690+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:13:43.653+0000] {processor.py:157} INFO - Started process (PID=2911) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T02:13:44.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T02:13:44.224+0000] {logging_mixin.py:151} INFO - [2025-04-23T02:13:44.073+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T03:07:21.227+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:08:38.574+0000] {processor.py:157} INFO - Started process (PID=2912) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:08:38.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:08:41.163+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:08:40.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:09:02.695+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:11:44.495+0000] {processor.py:157} INFO - Started process (PID=2922) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:11:45.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:11:46.509+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:11:45.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:12:02.343+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:13:24.042+0000] {processor.py:157} INFO - Started process (PID=2923) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:13:24.689+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:13:25.697+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:13:25.074+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:13:35.541+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:15:11.639+0000] {processor.py:157} INFO - Started process (PID=2925) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:15:13.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:15:14.577+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:15:13.695+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:17:04.026+0000] {processor.py:157} INFO - Started process (PID=2926) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:17:04.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:17:04.605+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:17:04.544+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:17:56.546+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:19:19.193+0000] {processor.py:157} INFO - Started process (PID=2927) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:19:19.811+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:19:20.008+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:19:19.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:19:44.327+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:21:02.875+0000] {processor.py:157} INFO - Started process (PID=2928) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:21:03.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:21:04.511+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:21:03.821+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:21:20.753+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:23:44.638+0000] {processor.py:157} INFO - Started process (PID=2929) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:23:46.567+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:23:47.781+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:23:47.247+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:24:04.268+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:26:45.047+0000] {processor.py:157} INFO - Started process (PID=2937) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:26:45.231+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:26:45.405+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:26:45.309+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:27:06.068+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:28:41.425+0000] {processor.py:157} INFO - Started process (PID=2944) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:28:41.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:28:41.727+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:28:41.705+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:31:29.656+0000] {processor.py:157} INFO - Started process (PID=2946) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:31:29.762+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:32:55.752+0000] {processor.py:157} INFO - Started process (PID=2947) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:32:56.079+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:32:56.135+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:32:56.090+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:33:00.958+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:35:30.462+0000] {processor.py:157} INFO - Started process (PID=2948) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:35:30.516+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:35:30.779+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:35:30.627+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:35:34.816+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:37:49.018+0000] {processor.py:157} INFO - Started process (PID=2949) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:37:49.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:37:49.069+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:37:49.066+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:38:09.354+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:41:18.098+0000] {processor.py:157} INFO - Started process (PID=2950) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:41:18.395+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:41:18.605+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:41:18.569+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:41:36.946+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:44:02.723+0000] {processor.py:157} INFO - Started process (PID=2951) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:44:05.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:44:07.828+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:44:05.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:44:29.096+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:45:51.044+0000] {processor.py:157} INFO - Started process (PID=2952) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:45:51.543+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:45:51.690+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:45:51.624+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:46:26.518+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:46:23.272+0000] {timeout.py:68} ERROR - Process timed out, PID: 2952
[2025-04-23T04:46:30.082+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:46:26.607+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/user_et_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_et_dag.py", line 2, in <module>
    from airflow.operators.python_operator import PythonOperator
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 212, in <module>
    class BranchPythonOperator(PythonOperator, SkipMixin):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 457, in __new__
    new_cls = super().__new__(cls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/user_et_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2952
[2025-04-23T04:46:32.225+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:49:38.401+0000] {processor.py:157} INFO - Started process (PID=2953) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T04:49:39.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T04:49:40.425+0000] {logging_mixin.py:151} INFO - [2025-04-23T04:49:40.197+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:09:46.185+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:12:53.554+0000] {processor.py:157} INFO - Started process (PID=2954) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:12:53.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:12:54.139+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:12:53.876+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:13:04.734+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:15:27.500+0000] {processor.py:157} INFO - Started process (PID=2955) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:15:27.545+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:15:28.326+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:15:27.592+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:15:42.202+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:17:16.304+0000] {processor.py:157} INFO - Started process (PID=2956) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:17:16.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:17:17.158+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:17:16.631+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:19:05.429+0000] {processor.py:157} INFO - Started process (PID=2957) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:19:05.451+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:19:05.649+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:19:05.458+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:19:10.076+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:21:43.084+0000] {processor.py:157} INFO - Started process (PID=2958) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:21:43.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:21:43.093+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:21:43.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:21:44.119+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:22:04.841+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:22:04.723+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T05:22:04.870+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:22:04.869+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T05:22:06.070+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:22:06.028+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-22T05:22:05.986111+00:00, run_after=2025-04-23T05:22:05.986111+00:00
[2025-04-23T05:22:58.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 26.026 seconds
[2025-04-23T05:24:21.627+0000] {processor.py:157} INFO - Started process (PID=2966) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:24:21.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:24:21.673+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:24:21.671+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:24:23.437+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:30:46.359+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:30:45.979+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T05:30:46.374+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:30:46.373+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T05:33:36.209+0000] {processor.py:157} INFO - Started process (PID=2967) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:33:36.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:33:37.508+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:33:37.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:35:06.971+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:35:03.222+0000] {timeout.py:68} ERROR - Process timed out, PID: 2967
[2025-04-23T05:35:38.914+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:35:10.599+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/user_et_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_et_dag.py", line 76, in <module>
    start_task = EmptyOperator(task_id='start')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 884, in __init__
    self.retry_delay = coerce_timedelta(retry_delay, key="retry_delay")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 136, in coerce_timedelta
    if isinstance(value, timedelta):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/user_et_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2967
[2025-04-23T05:35:42.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:36:18.945+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 625, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T05:38:40.215+0000] {processor.py:157} INFO - Started process (PID=2968) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:38:40.306+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:38:40.335+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:38:40.315+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:39:07.528+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:50:19.546+0000] {processor.py:157} INFO - Started process (PID=2969) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:50:19.560+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:50:19.595+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:50:19.581+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:52:09.817+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:54:12.233+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 669, in _sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 636, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T05:59:18.339+0000] {processor.py:157} INFO - Started process (PID=2970) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:59:19.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T05:59:33.714+0000] {logging_mixin.py:151} INFO - [2025-04-23T05:59:29.185+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T05:59:54.200+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:01:29.750+0000] {processor.py:157} INFO - Started process (PID=2971) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:01:30.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:01:30.655+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:01:30.642+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:01:34.279+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:11:32.343+0000] {processor.py:157} INFO - Started process (PID=2972) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:11:32.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:11:32.410+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:11:32.361+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:11:33.309+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:11:48.021+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:11:47.958+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T06:11:48.120+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:11:48.119+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T06:11:55.403+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:11:55.370+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T06:11:59.288+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 27.151 seconds
[2025-04-23T06:13:20.945+0000] {processor.py:157} INFO - Started process (PID=2973) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:13:20.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:13:20.991+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:13:20.977+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:13:52.954+0000] {processor.py:157} INFO - Started process (PID=2982) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:13:53.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:13:53.091+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:13:53.029+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:13:57.330+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:16:50.376+0000] {processor.py:157} INFO - Started process (PID=2983) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:16:50.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:16:50.516+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:16:50.484+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:16:54.790+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:16:58.241+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:16:58.224+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T06:16:58.254+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:16:58.247+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T06:16:58.632+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:16:58.626+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T06:16:58.901+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 9.776 seconds
[2025-04-23T06:18:11.459+0000] {processor.py:157} INFO - Started process (PID=2990) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:18:11.520+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:18:11.558+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:18:11.549+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:18:12.435+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:18:27.534+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:18:27.451+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T06:18:29.372+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:18:29.348+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T06:18:30.688+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 19.599 seconds
[2025-04-23T06:19:34.972+0000] {processor.py:157} INFO - Started process (PID=2991) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:19:35.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:19:35.648+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:19:35.278+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:19:37.328+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:22:40.616+0000] {processor.py:157} INFO - Started process (PID=2992) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:22:40.972+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:22:41.278+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:22:41.266+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:22:42.783+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:24:14.107+0000] {processor.py:157} INFO - Started process (PID=2993) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:24:14.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:24:14.280+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:24:14.271+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:24:18.606+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:26:23.191+0000] {processor.py:157} INFO - Started process (PID=2994) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T06:26:23.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T06:26:23.412+0000] {logging_mixin.py:151} INFO - [2025-04-23T06:26:23.290+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:00:08.258+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:00:03.119+0000] {timeout.py:68} ERROR - Process timed out, PID: 2994
[2025-04-23T12:00:15.938+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:00:10.566+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/user_et_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 971, in get_code
  File "<frozen importlib._bootstrap_external>", line 640, in _compile_bytecode
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/user_et_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 2994
[2025-04-23T12:00:16.950+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:03:02.984+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 625, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T12:06:24.024+0000] {processor.py:157} INFO - Started process (PID=2995) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:06:24.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:06:24.596+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:06:24.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:06:36.778+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:30:48.339+0000] {processor.py:157} INFO - Started process (PID=2996) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:30:49.213+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:31:01.374+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:30:51.911+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:38:04.145+0000] {processor.py:157} INFO - Started process (PID=2999) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:38:04.619+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:38:05.282+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:38:05.252+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:38:14.428+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:39:32.151+0000] {processor.py:157} INFO - Started process (PID=3000) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:39:32.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:39:32.679+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:39:32.577+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:39:37.488+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:41:00.882+0000] {processor.py:157} INFO - Started process (PID=3001) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:41:01.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:41:01.189+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:41:01.171+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:41:02.964+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:41:51.903+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 669, in _sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 636, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T12:42:51.710+0000] {processor.py:157} INFO - Started process (PID=3002) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:42:51.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:42:51.974+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:42:51.972+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:42:56.624+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:44:31.724+0000] {processor.py:157} INFO - Started process (PID=3003) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:44:31.788+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T12:44:31.989+0000] {logging_mixin.py:151} INFO - [2025-04-23T12:44:31.883+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T12:44:34.403+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:16:07.832+0000] {processor.py:157} INFO - Started process (PID=3004) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:16:08.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:16:08.253+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:16:08.095+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:16:13.093+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:17:39.058+0000] {processor.py:157} INFO - Started process (PID=3005) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:17:39.200+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:17:39.290+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:17:39.265+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:17:41.236+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:18:56.133+0000] {processor.py:157} INFO - Started process (PID=3006) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:18:56.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:18:57.621+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:18:56.493+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:19:00.193+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:20:33.492+0000] {processor.py:157} INFO - Started process (PID=3007) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:20:33.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:20:34.038+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:20:33.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:20:39.594+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:22:44.158+0000] {processor.py:157} INFO - Started process (PID=3008) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:22:44.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:23:18.346+0000] {processor.py:157} INFO - Started process (PID=3009) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:23:22.466+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:23:24.215+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:23:23.487+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:23:43.982+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:44:05.940+0000] {processor.py:157} INFO - Started process (PID=3010) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:44:07.199+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:44:10.797+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:44:09.211+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:44:44.169+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:56:42.573+0000] {processor.py:157} INFO - Started process (PID=3011) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:56:42.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:56:43.368+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:56:42.730+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:56:47.052+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:58:16.517+0000] {processor.py:157} INFO - Started process (PID=3012) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:58:18.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T13:58:35.816+0000] {logging_mixin.py:151} INFO - [2025-04-23T13:58:21.021+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:58:44.215+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T13:59:38.830+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 669, in _sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 636, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T14:01:20.188+0000] {processor.py:157} INFO - Started process (PID=3013) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:01:20.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:01:20.919+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:01:20.645+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:02:26.223+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:02:23.846+0000] {timeout.py:68} ERROR - Process timed out, PID: 3013
[2025-04-23T14:02:44.342+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:02:32.699+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/user_et_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/user_et_dag.py", line 83, in <module>
    load_task = PythonOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 177, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 805, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 56, in validate_key
    if not KEY_REGEX.match(k):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/user_et_dag.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.7.1/best-practices.html#reducing-dag-complexity, PID: 3013
[2025-04-23T14:02:48.291+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:03:14.881+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 842, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 625, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T14:04:59.617+0000] {processor.py:157} INFO - Started process (PID=3014) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:04:59.978+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:05:00.183+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:05:00.167+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:05:00.908+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:07:25.816+0000] {processor.py:157} INFO - Started process (PID=3015) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:07:25.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:07:26.259+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:07:26.083+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:07:30.791+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:08:16.088+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 669, in _sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 636, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T14:09:13.599+0000] {processor.py:157} INFO - Started process (PID=3016) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:09:14.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:09:22.978+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:09:20.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:09:36.348+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:10:39.242+0000] {processor.py:182} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 178, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 159, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 857, in process_file
    serialize_errors = DagFileProcessor.save_dag_to_db(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 893, in save_dag_to_db
    import_errors = DagBag._sync_to_db(dags=dags, processor_subdir=dag_directory, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 657, in _sync_to_db
    for attempt in run_with_db_retries(logger=log):
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "/home/airflow/.local/lib/python3.8/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 669, in _sync_to_db
    serialize_errors.extend(_serialize_dag_capturing_errors(dag, session))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 636, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 147, in write_dag
    if session.scalar(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1747, in scalar
    return self.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-04-23T14:11:45.474+0000] {processor.py:157} INFO - Started process (PID=3017) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:11:47.857+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:11:58.627+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:11:52.549+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:12:36.997+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:14:53.537+0000] {processor.py:157} INFO - Started process (PID=3018) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:14:53.725+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:14:53.903+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:14:53.744+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:14:55.336+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:15:28.245+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:15:28.167+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T14:15:28.438+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:15:28.379+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:15:37.224+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:15:37.206+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:15:38.364+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 45.603 seconds
[2025-04-23T14:16:11.592+0000] {processor.py:157} INFO - Started process (PID=3019) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:16:11.620+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:16:11.788+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:16:11.623+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:16:12.615+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:16:21.046+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:16:20.715+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:16:22.276+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:16:22.221+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:16:22.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 11.294 seconds
[2025-04-23T14:16:54.861+0000] {processor.py:157} INFO - Started process (PID=3020) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:16:54.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:16:54.966+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:16:54.889+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:16:56.081+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:23:31.359+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:23:31.402+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:23:31.443+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:23:31.442+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:23:31.693+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:23:33.455+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:23:33.453+0000] {security.py:708} INFO - Not syncing DAG-level permissions for DAG 'DAG:user_etl_dag' as access control is unset.
[2025-04-23T14:23:33.458+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:23:33.458+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:23:33.582+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:23:33.581+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:23:33.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 2.434 seconds
[2025-04-23T14:24:05.510+0000] {processor.py:157} INFO - Started process (PID=61) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:05.633+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:24:05.728+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:05.718+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:07.112+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:12.685+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:12.683+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:24:13.373+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:13.373+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:24:13.530+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 8.335 seconds
[2025-04-23T14:24:44.820+0000] {processor.py:157} INFO - Started process (PID=76) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:44.838+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:24:44.920+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:44.908+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:45.192+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:24:45.660+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:45.660+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:24:46.112+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:24:46.110+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:24:47.124+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 2.455 seconds
[2025-04-23T14:25:26.154+0000] {processor.py:157} INFO - Started process (PID=83) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:25:26.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:25:26.463+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:25:26.461+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:25:27.195+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:25:27.752+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:25:27.751+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:25:29.609+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:25:29.606+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:25:31.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 5.913 seconds
[2025-04-23T14:26:03.566+0000] {processor.py:157} INFO - Started process (PID=92) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:03.617+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:26:04.112+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:04.088+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:04.409+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:05.036+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:05.035+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:26:05.626+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:05.626+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:26:05.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 2.962 seconds
[2025-04-23T14:26:37.119+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:37.320+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:26:37.427+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:37.422+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:37.898+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:26:39.176+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:39.167+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:26:40.630+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:26:40.197+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:26:43.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 6.252 seconds
[2025-04-23T14:27:19.423+0000] {processor.py:157} INFO - Started process (PID=110) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:19.456+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:27:20.284+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:20.248+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:22.694+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:24.027+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:24.015+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:27:24.379+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:24.379+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:27:24.519+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 6.976 seconds
[2025-04-23T14:27:55.357+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:55.366+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:27:55.443+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:55.412+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:55.689+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:27:56.265+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:56.263+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:27:57.078+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:27:57.075+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:27:58.871+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 3.570 seconds
[2025-04-23T14:28:34.127+0000] {processor.py:157} INFO - Started process (PID=129) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:28:34.510+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:28:35.638+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:28:35.545+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:28:37.147+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:28:38.487+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:28:38.486+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:28:38.696+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:28:38.695+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:28:38.790+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 5.061 seconds
[2025-04-23T14:29:34.826+0000] {processor.py:157} INFO - Started process (PID=138) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:29:35.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:29:37.380+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:29:36.319+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:29:41.814+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:29:44.688+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:29:44.676+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:29:45.022+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:29:45.010+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:29:45.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 16.240 seconds
[2025-04-23T14:30:18.285+0000] {processor.py:157} INFO - Started process (PID=148) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:30:18.297+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:30:18.366+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:30:18.363+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:30:18.893+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:30:21.232+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:30:21.229+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:30:23.227+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:30:23.225+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:30:23.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 5.784 seconds
[2025-04-23T14:31:02.054+0000] {processor.py:157} INFO - Started process (PID=156) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:02.565+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:31:05.466+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:05.272+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:05.713+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:07.566+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:07.464+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:31:08.828+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:08.827+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:31:09.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 9.926 seconds
[2025-04-23T14:31:41.607+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:41.673+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:31:42.954+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:42.280+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:46.044+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:31:47.730+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:47.724+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:31:48.591+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:31:48.591+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:31:49.286+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 8.961 seconds
[2025-04-23T14:32:20.525+0000] {processor.py:157} INFO - Started process (PID=182) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:20.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:32:20.647+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:20.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:21.090+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:23.120+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:23.118+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:32:24.198+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:24.195+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:32:24.613+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 4.223 seconds
[2025-04-23T14:32:55.927+0000] {processor.py:157} INFO - Started process (PID=190) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:55.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:32:55.999+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:55.996+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:56.299+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:32:57.126+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:57.125+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:32:58.214+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:32:58.212+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:33:02.058+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 6.255 seconds
[2025-04-23T14:33:36.683+0000] {processor.py:157} INFO - Started process (PID=198) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:33:36.744+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:33:36.911+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:33:36.879+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:33:37.882+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:33:40.598+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:33:40.582+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:33:43.315+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:33:43.246+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:33:44.499+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 8.140 seconds
[2025-04-23T14:34:21.460+0000] {processor.py:157} INFO - Started process (PID=207) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:34:21.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:34:21.713+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:34:21.676+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:34:25.632+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:34:33.378+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:34:33.183+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:34:42.454+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:34:42.447+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:34:48.620+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 27.681 seconds
[2025-04-23T14:35:31.243+0000] {processor.py:157} INFO - Started process (PID=213) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:35:31.415+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:35:31.813+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:35:31.756+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:35:32.478+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:35:33.919+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:35:33.908+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:35:34.334+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:35:34.331+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:35:34.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 4.577 seconds
[2025-04-23T14:36:10.182+0000] {processor.py:157} INFO - Started process (PID=222) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:10.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:36:10.830+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:10.744+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:11.848+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:12.521+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:12.520+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:36:13.639+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:13.637+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:36:13.834+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 4.073 seconds
[2025-04-23T14:36:47.161+0000] {processor.py:157} INFO - Started process (PID=231) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:47.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:36:47.404+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:47.402+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:47.917+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:36:48.666+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:48.665+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:36:50.691+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:36:50.686+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:36:51.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 4.570 seconds
[2025-04-23T14:37:26.530+0000] {processor.py:157} INFO - Started process (PID=241) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:37:26.593+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:37:26.984+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:37:26.977+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:37:28.444+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:37:30.273+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:37:30.272+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:37:31.187+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:37:31.186+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:37:31.660+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 5.981 seconds
[2025-04-23T14:38:02.941+0000] {processor.py:157} INFO - Started process (PID=249) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:02.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:38:03.202+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:03.174+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:03.769+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:04.685+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:04.684+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:38:05.248+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:05.247+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:38:05.592+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 2.958 seconds
[2025-04-23T14:38:43.396+0000] {processor.py:157} INFO - Started process (PID=258) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:43.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:38:43.912+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:43.906+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:45.111+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:38:46.007+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:46.001+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:38:46.311+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:38:46.310+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:38:46.494+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 3.166 seconds
[2025-04-23T14:39:18.317+0000] {processor.py:157} INFO - Started process (PID=266) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:39:18.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:39:18.597+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:39:18.581+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:39:21.281+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:39:24.668+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:39:24.663+0000] {dag.py:2915} INFO - Sync 1 DAGs
[2025-04-23T14:39:30.317+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:39:30.174+0000] {dag.py:3696} INFO - Setting next_dagrun for user_etl_dag to 2025-04-23T05:22:05.986111+00:00, run_after=2025-04-24T05:22:05.986111+00:00
[2025-04-23T14:39:35.656+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/user_et_dag.py took 17.636 seconds
[2025-04-23T14:40:34.554+0000] {processor.py:157} INFO - Started process (PID=274) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:40:36.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:40:55.306+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:40:52.357+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:41:39.155+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:41:39.738+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:41:44.747+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:41:44.374+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:41:51.109+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:43:27.315+0000] {processor.py:157} INFO - Started process (PID=283) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:43:27.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:43:27.988+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:43:27.603+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:43:32.842+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:44:53.409+0000] {processor.py:157} INFO - Started process (PID=284) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:44:53.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:44:55.457+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:44:54.593+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:45:06.539+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:46:15.750+0000] {processor.py:157} INFO - Started process (PID=285) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:46:16.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:46:16.671+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:46:16.411+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:46:30.887+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:47:51.467+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:47:51.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:47:51.916+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:47:51.645+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:48:04.618+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:49:03.393+0000] {processor.py:157} INFO - Started process (PID=293) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:49:04.422+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:49:05.941+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:49:05.293+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:49:21.452+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:50:25.094+0000] {processor.py:157} INFO - Started process (PID=310) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:50:25.252+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:50:25.542+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:50:25.396+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:50:32.694+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:51:51.956+0000] {processor.py:157} INFO - Started process (PID=319) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:51:53.000+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:51:54.447+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:51:54.069+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:52:10.277+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:54:33.432+0000] {processor.py:157} INFO - Started process (PID=327) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:54:33.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:54:33.837+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:54:33.641+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:54:43.172+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:56:02.662+0000] {processor.py:157} INFO - Started process (PID=328) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:56:02.774+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:56:03.127+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:56:02.815+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:56:12.315+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:58:02.269+0000] {processor.py:157} INFO - Started process (PID=329) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T14:58:10.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T14:58:24.063+0000] {logging_mixin.py:151} INFO - [2025-04-23T14:58:20.432+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:00:27.771+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:01:59.821+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:02:00.217+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:02:02.558+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:02:01.374+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:03:05.718+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:02:58.722+0000] {timeout.py:68} ERROR - Process timed out, PID: 330
[2025-04-23T15:03:57.724+0000] {processor.py:157} INFO - Started process (PID=331) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:03:58.268+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:03:58.626+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:03:58.495+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:04:33.544+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:05:23.806+0000] {processor.py:157} INFO - Started process (PID=332) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:05:23.859+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:05:24.195+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:05:23.990+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:05:47.389+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:07:03.759+0000] {processor.py:157} INFO - Started process (PID=333) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:07:04.917+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:07:06.038+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:07:05.428+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:07:58.124+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:07:45.642+0000] {timeout.py:68} ERROR - Process timed out, PID: 333
[2025-04-23T15:09:56.385+0000] {processor.py:157} INFO - Started process (PID=334) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:10:04.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:10:44.541+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:10:30.982+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:11:46.933+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:11:47.119+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:11:53.042+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:11:48.914+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:12:14.595+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:13:22.224+0000] {processor.py:157} INFO - Started process (PID=336) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:13:23.477+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:13:26.719+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:13:24.891+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:13:49.971+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:14:33.026+0000] {processor.py:157} INFO - Started process (PID=343) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:14:33.077+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:14:33.202+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:14:33.135+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:14:53.588+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:16:28.887+0000] {processor.py:157} INFO - Started process (PID=344) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:16:28.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:16:29.037+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:16:28.993+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:17:48.195+0000] {processor.py:839} INFO - DAG(s) dict_keys(['user_etl_dag']) retrieved from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:19:16.733+0000] {processor.py:157} INFO - Started process (PID=345) to work on /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:19:21.547+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/user_et_dag.py for tasks to queue
[2025-04-23T15:19:32.752+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:19:25.803+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/user_et_dag.py
[2025-04-23T15:20:49.531+0000] {logging_mixin.py:151} INFO - [2025-04-23T15:20:31.694+0000] {timeout.py:68} ERROR - Process timed out, PID: 345
